//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visus.DirectoryAuthentication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visus.DirectoryAuthentication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP attribute &quot;{0}&quot; was not found while assigning properties..
        /// </summary>
        internal static string ErrorAttributeNotFound {
            get {
                return ResourceManager.GetString("ErrorAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP SSL certificate is not valid after {0}..
        /// </summary>
        internal static string ErrorCertificateExpired {
            get {
                return ResourceManager.GetString("ErrorCertificateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP SSL certificate is not valid before {0}..
        /// </summary>
        internal static string ErrorCertificateNotYetValid {
            get {
                return ResourceManager.GetString("ErrorCertificateNotYetValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP SSL certificate has not been issued by &quot;{0}&quot;, but by &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorCertIssuerMismatch {
            get {
                return ResourceManager.GetString("ErrorCertIssuerMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP SSL certificate has the thumbprint &quot;{0}&quot;, which is not one of the expected ones..
        /// </summary>
        internal static string ErrorCertThumbprintMismatch {
            get {
                return ResourceManager.GetString("ErrorCertThumbprintMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the LDAP service account must be specified if a service user is configured..
        /// </summary>
        internal static string ErrorEmptyPassword {
            get {
                return ResourceManager.GetString("ErrorEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search base must be a non-empty string..
        /// </summary>
        internal static string ErrorEmptySearchBase {
            get {
                return ResourceManager.GetString("ErrorEmptySearchBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry matching {0} does not exist in the directory in the specified search locations..
        /// </summary>
        internal static string ErrorEntryNotFound {
            get {
                return ResourceManager.GetString("ErrorEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve group claim for &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorGroupClaim {
            get {
                return ResourceManager.GetString("ErrorGroupClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group with identity &quot;{group}&quot; was not found in the directory..
        /// </summary>
        internal static string ErrorGroupNotFound {
            get {
                return ResourceManager.GetString("ErrorGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given byte sequence &quot;{0}&quot; does not represent a valid security identifier..
        /// </summary>
        internal static string ErrorInvalidSid {
            get {
                return ResourceManager.GetString("ErrorInvalidSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default LdapOptions cannot be registered as interface, because this would result in an ambiguous constructor call. Use the non-generic variant of AddLdapOptions to register the default options type..
        /// </summary>
        internal static string ErrorLdapOptionsRegistration {
            get {
                return ResourceManager.GetString("ErrorLdapOptionsRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging of LDAP search results must start at 0..
        /// </summary>
        internal static string ErrorLdapPage {
            get {
                return ResourceManager.GetString("ErrorLdapPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of a page of LDAP search results must be at least 1..
        /// </summary>
        internal static string ErrorLdapPageSize {
            get {
                return ResourceManager.GetString("ErrorLdapPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not annotated with an account name attribute..
        /// </summary>
        internal static string ErrorNoAccountName {
            get {
                return ResourceManager.GetString("ErrorNoAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not annotated with a unique LdapIdentity attribute..
        /// </summary>
        internal static string ErrorNoIdentity {
            get {
                return ResourceManager.GetString("ErrorNoIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} is not annotated with an LdapAttribute attribute..
        /// </summary>
        internal static string ErrorNoLdapAttribute {
            get {
                return ResourceManager.GetString("ErrorNoLdapAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid mapping has been configured..
        /// </summary>
        internal static string ErrorNoMapping {
            get {
                return ResourceManager.GetString("ErrorNoMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password attribute is not configured, but it is required..
        /// </summary>
        internal static string ErrorNoPasswordAttribute {
            get {
                return ResourceManager.GetString("ErrorNoPasswordAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the primary group claim for &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorPrimaryGroupClaim {
            get {
                return ResourceManager.GetString("ErrorPrimaryGroupClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary group of the given entry could not be retrieved..
        /// </summary>
        internal static string ErrorPrimaryGroupNotFound {
            get {
                return ResourceManager.GetString("ErrorPrimaryGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given property &quot;{0}&quot; was not found..
        /// </summary>
        internal static string ErrorPropertyNotFound {
            get {
                return ResourceManager.GetString("ErrorPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given property &quot;{0}&quot; has no LDAP attribute mapped for the current schema &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorPropertyNotMapped {
            get {
                return ResourceManager.GetString("ErrorPropertyNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login succeeded, but your user information could not be retrieved..
        /// </summary>
        internal static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login of &quot;{0}&quot; succeeded, but the user information could not be retrieved. This usually indicates a misconfiguration of the search bases. Make sure that all user accounts that should be able to login are located in one of the configured search bases. Another potential isse is the UserFilter in the application settings not covering all valid input formats for a user name..
        /// </summary>
        internal static string ErrorUserNotFoundDetailed {
            get {
                return ResourceManager.GetString("ErrorUserNotFoundDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing anonyomous bind..
        /// </summary>
        internal static string InfoBindAnonymous {
            get {
                return ResourceManager.GetString("InfoBindAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing LDAP bind as user &quot;{0}&quot;..
        /// </summary>
        internal static string InfoBindingAsUser {
            get {
                return ResourceManager.GetString("InfoBindingAsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous bind succeeded..
        /// </summary>
        internal static string InfoBoundAnonymous {
            get {
                return ResourceManager.GetString("InfoBoundAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated successfully as user &quot;{0}&quot;..
        /// </summary>
        internal static string InfoBoundAsUser {
            get {
                return ResourceManager.GetString("InfoBoundAsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for LDAP server certificate &quot;{0}&quot; being issued by &quot;{1}&quot;..
        /// </summary>
        internal static string InfoCheckCertIssuer {
            get {
                return ResourceManager.GetString("InfoCheckCertIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that LDAP server &quot;certificate {0} has one of the following thumbprints: {1}.
        /// </summary>
        internal static string InfoCheckCertThumbprint {
            get {
                return ResourceManager.GetString("InfoCheckCertThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to LDAP server {0}:{1}..
        /// </summary>
        internal static string InfoConnectingLdap {
            get {
                return ResourceManager.GetString("InfoConnectingLdap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP SSL certificate check has been disabled..
        /// </summary>
        internal static string WarnCertCheckDisabled {
            get {
                return ResourceManager.GetString("WarnCertCheckDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL is most likely not working due to https://github.com/dotnet/runtime/issues/43890..
        /// </summary>
        internal static string WarnNoSsl {
            get {
                return ResourceManager.GetString("WarnNoSsl", resourceCulture);
            }
        }
    }
}
